### ISSUE TITLE
No output on Intel 2127U

### ISSUE THREAD

**Issue by Unesty** [st3r4g/swvkc#1]
Wayland clients work, but there is no graphics output.

**Comment by st3r4g** [comment]
Do you see the grey background or not even that?

**Comment by Unesty** [comment]
Not even that.

**Comment by Unesty** [comment]
[stdout](https://raw.githubusercontent.com/Unesty/MyProject5/master/swvkc%20stout)
[stderr](https://raw.githubusercontent.com/Unesty/MyProject5/master/two)
[strace](https://raw.githubusercontent.com/Unesty/MyProject5/master/swvkc.log)

**Comment by st3r4g** [comment]
Yeah this happens with my laptop GPU as well. It is failing at the log line:

> AddFB: Invalid argument

which happens when `drmModeAddFB2WithModifiers` is called. I'll try to explain the issue:

At the moment the Vulkan extension that allows importing buffers with modifiers (tiled buffers) has not been merged in mesa yet (see https://gitlab.freedesktop.org/mesa/mesa/merge_requests/515), although the proposed implementation works (I tested it by compiling mesa by myself with that PR merged). You can see this in the log:

> [1014777.246] Extension VK_EXT_image_drm_format_modifier is NOT supported
> ...
> [1014788.998] swvkc DMABUF with MODIFIERS support: DISABLED

which means that the program is forced to create a **linear** GBM buffer, which doesn't require modifiers so that it can be imported in Vulkan for rendering. But for some reason DRM is unable to present this linear buffer to the screen, failing at the previously mentioned function call.

This will be solved once mesa merges the `VK_EXT_image_drm_format_modifier` extension implementation.

I don't know if I'm doing something wrong or it is simply that the scanout of linear buffers is not supported by the driver, you can try to obtain some more info if you enable the drm debug kernel log by appending the following to the kernel parameter list: `drm.debug=0x1e log_buf_len=1M` and checking `dmesg` for the line where it complains about the framebuffer before failing the commit. I did this but the error message wasn't really helpful (I don't remember what it was saying).

**Comment by st3r4g** [comment]
This is the relevant line in the kernel log:

> [drm:intel_framebuffer_init [i915]] plane 0 pitch (5464) must be at least 64 byte aligned

When GBM is told to create a linear buffer (with `GBM_BO_USE_LINEAR`), it creates one that has an incompatible pitch... I'm passing `GBM_BO_USE_SCANOUT` too, but that doesn't seem to help.

**Comment by st3r4g** [comment]
I tried to use the intel-specific function `drm_intel_bo_alloc_tiled` with `I915_TILING_NONE` and it creates a buffer with the correct (64 byte aligned) pitch, so I suspect GBM is doing something strange.

**Comment by Unesty** [comment]
Now it works, but last pixels are black. weston-simple-egl works properly, but with tearing. weston-simple-dmabuf-drm rendered like a ladder.
![IMG_20190729_224642](https://user-images.githubusercontent.com/12433033/62079370-3dc91d00-b257-11e9-8b72-6bddb11c61ed.jpg)
![weston-simple-egl](https://github.com/Unesty/MyProject5/raw/master/IMG_20190729_224839.jpg)

**Comment by Unesty** [comment]
Anyway, now there is graphical output on this GPU!
