### ISSUE TITLE
What is the reason of splitting code into separate object files?

### ISSUE THREAD

**Issue by Unesty** [st3r4g/swvkc#2]
Link time optimization can be enabled.

**Comment by st3r4g** [comment]
I wanted to separate the main program from the Wayland implementation. I didn't think about compiler optimizations. Is there a big difference?

**Comment by Unesty** [comment]
Without lto swvkc is about 20% bigger, which is caused by splitting into separate object files. Also more object files compile slower.

**Comment by st3r4g** [comment]
Well, I have separate object files because I cannot put all the code in one single source file. I don't want optimizations enabled by default for debugging reasons, but one can pass appropriate options to the meson command (such as `meson -Dbuildtype=release -Db_lto=true build`). So are you suggesting that I should add this flags in the Building section of the README?

**Comment by Unesty** [comment]
yes

**Comment by st3r4g** [comment]
Done. Thanks!
