### ISSUE TITLE
Device search should check for existence of devices

### ISSUE THREAD

**Issue by Unesty** [st3r4g/swvkc#3]
When udev is not running this swvkc print deleted divices as option.

**Comment by st3r4g** [comment]
Sorry, I didn't understand. Could you provide more information about the issue?

**Comment by Unesty** [comment]
killall udevd
rm /dev/input/event6
swvkc
choose keyboard
/dev/input/event6
/dev/input/event3

**Comment by st3r4g** [comment]
This is probably because I use `libudev` for device search and it gets information from the `/sys` filesystem, which is still there. But why would you want to manually remove an entry in `/dev` instead of just disconnecting the keyboard? I mean, the device is still there for the kernel, you just removed the reference under `/dev` so `swvkc` can't open it anymore.
